/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as EthereumRouteImport } from './routes/ethereum'
import { Route as BitcoinRouteImport } from './routes/bitcoin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecurityIndexRouteImport } from './routes/security.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as EthereumIndexRouteImport } from './routes/ethereum.index'
import { Route as BitcoinIndexRouteImport } from './routes/bitcoin.index'
import { Route as SecurityHowToStoreCryptoSeedPhraseSafelyRouteImport } from './routes/security.how-to-store-crypto-seed-phrase-safely'
import { Route as SecurityHowToAvoidCryptoPhishingScamsRouteImport } from './routes/security.how-to-avoid-crypto-phishing-scams'
import { Route as NewsWhyGovernmentsRegulateCryptocurrencyRouteImport } from './routes/news.why-governments-regulate-cryptocurrency'
import { Route as GuidesNotYourKeysNotYourCoinsMeaningRouteImport } from './routes/guides.not-your-keys-not-your-coins-meaning'
import { Route as EthereumCanYouSendBitcoinToAnEthereumAddressRouteImport } from './routes/ethereum.can-you-send-bitcoin-to-an-ethereum-address'
import { Route as BitcoinHowToSendBitcoinSafelyRouteImport } from './routes/bitcoin.how-to-send-bitcoin-safely'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const EthereumRoute = EthereumRouteImport.update({
  id: '/ethereum',
  path: '/ethereum',
  getParentRoute: () => rootRouteImport,
} as any)
const BitcoinRoute = BitcoinRouteImport.update({
  id: '/bitcoin',
  path: '/bitcoin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecurityRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const EthereumIndexRoute = EthereumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EthereumRoute,
} as any)
const BitcoinIndexRoute = BitcoinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BitcoinRoute,
} as any)
const SecurityHowToStoreCryptoSeedPhraseSafelyRoute =
  SecurityHowToStoreCryptoSeedPhraseSafelyRouteImport.update({
    id: '/how-to-store-crypto-seed-phrase-safely',
    path: '/how-to-store-crypto-seed-phrase-safely',
    getParentRoute: () => SecurityRoute,
  } as any)
const SecurityHowToAvoidCryptoPhishingScamsRoute =
  SecurityHowToAvoidCryptoPhishingScamsRouteImport.update({
    id: '/how-to-avoid-crypto-phishing-scams',
    path: '/how-to-avoid-crypto-phishing-scams',
    getParentRoute: () => SecurityRoute,
  } as any)
const NewsWhyGovernmentsRegulateCryptocurrencyRoute =
  NewsWhyGovernmentsRegulateCryptocurrencyRouteImport.update({
    id: '/why-governments-regulate-cryptocurrency',
    path: '/why-governments-regulate-cryptocurrency',
    getParentRoute: () => NewsRoute,
  } as any)
const GuidesNotYourKeysNotYourCoinsMeaningRoute =
  GuidesNotYourKeysNotYourCoinsMeaningRouteImport.update({
    id: '/not-your-keys-not-your-coins-meaning',
    path: '/not-your-keys-not-your-coins-meaning',
    getParentRoute: () => GuidesRoute,
  } as any)
const EthereumCanYouSendBitcoinToAnEthereumAddressRoute =
  EthereumCanYouSendBitcoinToAnEthereumAddressRouteImport.update({
    id: '/can-you-send-bitcoin-to-an-ethereum-address',
    path: '/can-you-send-bitcoin-to-an-ethereum-address',
    getParentRoute: () => EthereumRoute,
  } as any)
const BitcoinHowToSendBitcoinSafelyRoute =
  BitcoinHowToSendBitcoinSafelyRouteImport.update({
    id: '/how-to-send-bitcoin-safely',
    path: '/how-to-send-bitcoin-safely',
    getParentRoute: () => BitcoinRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bitcoin': typeof BitcoinRouteWithChildren
  '/ethereum': typeof EthereumRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/bitcoin/how-to-send-bitcoin-safely': typeof BitcoinHowToSendBitcoinSafelyRoute
  '/ethereum/can-you-send-bitcoin-to-an-ethereum-address': typeof EthereumCanYouSendBitcoinToAnEthereumAddressRoute
  '/guides/not-your-keys-not-your-coins-meaning': typeof GuidesNotYourKeysNotYourCoinsMeaningRoute
  '/news/why-governments-regulate-cryptocurrency': typeof NewsWhyGovernmentsRegulateCryptocurrencyRoute
  '/security/how-to-avoid-crypto-phishing-scams': typeof SecurityHowToAvoidCryptoPhishingScamsRoute
  '/security/how-to-store-crypto-seed-phrase-safely': typeof SecurityHowToStoreCryptoSeedPhraseSafelyRoute
  '/bitcoin/': typeof BitcoinIndexRoute
  '/ethereum/': typeof EthereumIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/bitcoin/how-to-send-bitcoin-safely': typeof BitcoinHowToSendBitcoinSafelyRoute
  '/ethereum/can-you-send-bitcoin-to-an-ethereum-address': typeof EthereumCanYouSendBitcoinToAnEthereumAddressRoute
  '/guides/not-your-keys-not-your-coins-meaning': typeof GuidesNotYourKeysNotYourCoinsMeaningRoute
  '/news/why-governments-regulate-cryptocurrency': typeof NewsWhyGovernmentsRegulateCryptocurrencyRoute
  '/security/how-to-avoid-crypto-phishing-scams': typeof SecurityHowToAvoidCryptoPhishingScamsRoute
  '/security/how-to-store-crypto-seed-phrase-safely': typeof SecurityHowToStoreCryptoSeedPhraseSafelyRoute
  '/bitcoin': typeof BitcoinIndexRoute
  '/ethereum': typeof EthereumIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/news': typeof NewsIndexRoute
  '/security': typeof SecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bitcoin': typeof BitcoinRouteWithChildren
  '/ethereum': typeof EthereumRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/bitcoin/how-to-send-bitcoin-safely': typeof BitcoinHowToSendBitcoinSafelyRoute
  '/ethereum/can-you-send-bitcoin-to-an-ethereum-address': typeof EthereumCanYouSendBitcoinToAnEthereumAddressRoute
  '/guides/not-your-keys-not-your-coins-meaning': typeof GuidesNotYourKeysNotYourCoinsMeaningRoute
  '/news/why-governments-regulate-cryptocurrency': typeof NewsWhyGovernmentsRegulateCryptocurrencyRoute
  '/security/how-to-avoid-crypto-phishing-scams': typeof SecurityHowToAvoidCryptoPhishingScamsRoute
  '/security/how-to-store-crypto-seed-phrase-safely': typeof SecurityHowToStoreCryptoSeedPhraseSafelyRoute
  '/bitcoin/': typeof BitcoinIndexRoute
  '/ethereum/': typeof EthereumIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/news/': typeof NewsIndexRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bitcoin'
    | '/ethereum'
    | '/guides'
    | '/news'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/bitcoin/how-to-send-bitcoin-safely'
    | '/ethereum/can-you-send-bitcoin-to-an-ethereum-address'
    | '/guides/not-your-keys-not-your-coins-meaning'
    | '/news/why-governments-regulate-cryptocurrency'
    | '/security/how-to-avoid-crypto-phishing-scams'
    | '/security/how-to-store-crypto-seed-phrase-safely'
    | '/bitcoin/'
    | '/ethereum/'
    | '/guides/'
    | '/news/'
    | '/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/bitcoin/how-to-send-bitcoin-safely'
    | '/ethereum/can-you-send-bitcoin-to-an-ethereum-address'
    | '/guides/not-your-keys-not-your-coins-meaning'
    | '/news/why-governments-regulate-cryptocurrency'
    | '/security/how-to-avoid-crypto-phishing-scams'
    | '/security/how-to-store-crypto-seed-phrase-safely'
    | '/bitcoin'
    | '/ethereum'
    | '/guides'
    | '/news'
    | '/security'
  id:
    | '__root__'
    | '/'
    | '/bitcoin'
    | '/ethereum'
    | '/guides'
    | '/news'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/bitcoin/how-to-send-bitcoin-safely'
    | '/ethereum/can-you-send-bitcoin-to-an-ethereum-address'
    | '/guides/not-your-keys-not-your-coins-meaning'
    | '/news/why-governments-regulate-cryptocurrency'
    | '/security/how-to-avoid-crypto-phishing-scams'
    | '/security/how-to-store-crypto-seed-phrase-safely'
    | '/bitcoin/'
    | '/ethereum/'
    | '/guides/'
    | '/news/'
    | '/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BitcoinRoute: typeof BitcoinRouteWithChildren
  EthereumRoute: typeof EthereumRouteWithChildren
  GuidesRoute: typeof GuidesRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethereum': {
      id: '/ethereum'
      path: '/ethereum'
      fullPath: '/ethereum'
      preLoaderRoute: typeof EthereumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitcoin': {
      id: '/bitcoin'
      path: '/bitcoin'
      fullPath: '/bitcoin'
      preLoaderRoute: typeof BitcoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/ethereum/': {
      id: '/ethereum/'
      path: '/'
      fullPath: '/ethereum/'
      preLoaderRoute: typeof EthereumIndexRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/bitcoin/': {
      id: '/bitcoin/'
      path: '/'
      fullPath: '/bitcoin/'
      preLoaderRoute: typeof BitcoinIndexRouteImport
      parentRoute: typeof BitcoinRoute
    }
    '/security/how-to-store-crypto-seed-phrase-safely': {
      id: '/security/how-to-store-crypto-seed-phrase-safely'
      path: '/how-to-store-crypto-seed-phrase-safely'
      fullPath: '/security/how-to-store-crypto-seed-phrase-safely'
      preLoaderRoute: typeof SecurityHowToStoreCryptoSeedPhraseSafelyRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/security/how-to-avoid-crypto-phishing-scams': {
      id: '/security/how-to-avoid-crypto-phishing-scams'
      path: '/how-to-avoid-crypto-phishing-scams'
      fullPath: '/security/how-to-avoid-crypto-phishing-scams'
      preLoaderRoute: typeof SecurityHowToAvoidCryptoPhishingScamsRouteImport
      parentRoute: typeof SecurityRoute
    }
    '/news/why-governments-regulate-cryptocurrency': {
      id: '/news/why-governments-regulate-cryptocurrency'
      path: '/why-governments-regulate-cryptocurrency'
      fullPath: '/news/why-governments-regulate-cryptocurrency'
      preLoaderRoute: typeof NewsWhyGovernmentsRegulateCryptocurrencyRouteImport
      parentRoute: typeof NewsRoute
    }
    '/guides/not-your-keys-not-your-coins-meaning': {
      id: '/guides/not-your-keys-not-your-coins-meaning'
      path: '/not-your-keys-not-your-coins-meaning'
      fullPath: '/guides/not-your-keys-not-your-coins-meaning'
      preLoaderRoute: typeof GuidesNotYourKeysNotYourCoinsMeaningRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/ethereum/can-you-send-bitcoin-to-an-ethereum-address': {
      id: '/ethereum/can-you-send-bitcoin-to-an-ethereum-address'
      path: '/can-you-send-bitcoin-to-an-ethereum-address'
      fullPath: '/ethereum/can-you-send-bitcoin-to-an-ethereum-address'
      preLoaderRoute: typeof EthereumCanYouSendBitcoinToAnEthereumAddressRouteImport
      parentRoute: typeof EthereumRoute
    }
    '/bitcoin/how-to-send-bitcoin-safely': {
      id: '/bitcoin/how-to-send-bitcoin-safely'
      path: '/how-to-send-bitcoin-safely'
      fullPath: '/bitcoin/how-to-send-bitcoin-safely'
      preLoaderRoute: typeof BitcoinHowToSendBitcoinSafelyRouteImport
      parentRoute: typeof BitcoinRoute
    }
  }
}

interface BitcoinRouteChildren {
  BitcoinHowToSendBitcoinSafelyRoute: typeof BitcoinHowToSendBitcoinSafelyRoute
  BitcoinIndexRoute: typeof BitcoinIndexRoute
}

const BitcoinRouteChildren: BitcoinRouteChildren = {
  BitcoinHowToSendBitcoinSafelyRoute: BitcoinHowToSendBitcoinSafelyRoute,
  BitcoinIndexRoute: BitcoinIndexRoute,
}

const BitcoinRouteWithChildren =
  BitcoinRoute._addFileChildren(BitcoinRouteChildren)

interface EthereumRouteChildren {
  EthereumCanYouSendBitcoinToAnEthereumAddressRoute: typeof EthereumCanYouSendBitcoinToAnEthereumAddressRoute
  EthereumIndexRoute: typeof EthereumIndexRoute
}

const EthereumRouteChildren: EthereumRouteChildren = {
  EthereumCanYouSendBitcoinToAnEthereumAddressRoute:
    EthereumCanYouSendBitcoinToAnEthereumAddressRoute,
  EthereumIndexRoute: EthereumIndexRoute,
}

const EthereumRouteWithChildren = EthereumRoute._addFileChildren(
  EthereumRouteChildren,
)

interface GuidesRouteChildren {
  GuidesNotYourKeysNotYourCoinsMeaningRoute: typeof GuidesNotYourKeysNotYourCoinsMeaningRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesNotYourKeysNotYourCoinsMeaningRoute:
    GuidesNotYourKeysNotYourCoinsMeaningRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface NewsRouteChildren {
  NewsWhyGovernmentsRegulateCryptocurrencyRoute: typeof NewsWhyGovernmentsRegulateCryptocurrencyRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsWhyGovernmentsRegulateCryptocurrencyRoute:
    NewsWhyGovernmentsRegulateCryptocurrencyRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface SecurityRouteChildren {
  SecurityHowToAvoidCryptoPhishingScamsRoute: typeof SecurityHowToAvoidCryptoPhishingScamsRoute
  SecurityHowToStoreCryptoSeedPhraseSafelyRoute: typeof SecurityHowToStoreCryptoSeedPhraseSafelyRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
}

const SecurityRouteChildren: SecurityRouteChildren = {
  SecurityHowToAvoidCryptoPhishingScamsRoute:
    SecurityHowToAvoidCryptoPhishingScamsRoute,
  SecurityHowToStoreCryptoSeedPhraseSafelyRoute:
    SecurityHowToStoreCryptoSeedPhraseSafelyRoute,
  SecurityIndexRoute: SecurityIndexRoute,
}

const SecurityRouteWithChildren = SecurityRoute._addFileChildren(
  SecurityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BitcoinRoute: BitcoinRouteWithChildren,
  EthereumRoute: EthereumRouteWithChildren,
  GuidesRoute: GuidesRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
